# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "sunya9"
    groups:
      unified-packages:
        patterns:
          - "rehype-img-size"
          - "rehype-pretty-code"
          - "rehype-slug"
          - "rehype-unwrap-images"
          - "shiki"
      next-packages:
        patterns:
          - "react*"
          - "@types/react*"
          - "next*"
          - "eslint-config-next"

      dev-packages:
        patterns:
          - "@types/node"
          - "@types/recursive-readdir"
          - "@types/rss"
          - "@types/write-file-webpack-plugin"
          - "autoprefixer"
          - "eslint"
          - "eslint-config-next"
          - "eslint-config-prettier"
          - "postcss"
          - "postcss-flexbugs-fixes"
          - "postcss-preset-env"
          - "prettier"
          - "prettier-plugin-tailwindcss*"
          - "typescript*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "sunya9"
